# Generated by Django 4.0.4 on 2022-04-20 05:56

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(default=products.models.generate_product_id, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]



